// lib/ledger/types.ts

/**
 * Event types for the Bickford ledger system
 * All events are append-only and immutable
 */
export type LedgerEventType =
  | "EXECUTION_STARTED"
  | "PLAN_GENERATED"
  | "FILES_APPLIED"
  | "DEPLOY_TRIGGERED"
  | "DEPLOY_COMPLETE"
  | "ROLLBACK_EXECUTED";

/**
 * Base structure for all ledger events
 */
export interface LedgerEvent {
  type: LedgerEventType;
  executionId: string;
  timestamp: string;
  [key: string]: unknown;
}

/**
 * Event: Execution flow started
 */
export interface ExecutionStartedEvent extends LedgerEvent {
  type: "EXECUTION_STARTED";
  intent: string;
}

/**
 * Event: Plan generated by Claude
 */
export interface PlanGeneratedEvent extends LedgerEvent {
  type: "PLAN_GENERATED";
  plan: {
    summary: string;
    files: Array<{ path: string; content: string }>;
    requiresDeploy: boolean;
  };
  canonDecision: string;
  canonRationale: string;
}

/**
 * Event: Files applied to filesystem
 */
export interface FilesAppliedEvent extends LedgerEvent {
  type: "FILES_APPLIED";
  diff: string;
  commitSha?: string;
}

/**
 * Event: Deploy triggered
 */
export interface DeployTriggeredEvent extends LedgerEvent {
  type: "DEPLOY_TRIGGERED";
  deployUrl: string;
}

/**
 * Event: Deploy completed successfully
 */
export interface DeployCompleteEvent extends LedgerEvent {
  type: "DEPLOY_COMPLETE";
  deployUrl: string;
  status: string;
}

/**
 * Event: Rollback executed
 */
export interface RollbackExecutedEvent extends LedgerEvent {
  type: "ROLLBACK_EXECUTED";
  reason: string;
  previousCommit: string;
}
